INSERT INTO person_tb (first_name, last_name, address, gender) VALUES
('John', 'Doe', '123 Elm Street, Springfield, IL', 'Male'),
('Jane', 'Smith', '456 Oak Avenue, San Francisco, CA', 'Female'),
('Michael', 'Johnson', '789 Pine Lane, Austin, TX', 'Male'),
('Emily', 'Davis', '101 Maple Road, New York, NY', 'Female'),
('David', 'Brown', '202 Birch Boulevard, Denver, CO', 'Male'),
('Sophia', 'Wilson', '303 Cedar Drive, Miami, FL', 'Female'),
('James', 'Miller', '404 Redwood Street, Seattle, WA', 'Male'),
('Olivia', 'Taylor', '505 Aspen Court, Chicago, IL', 'Female'),
('Daniel', 'Anderson', '606 Spruce Way, Boston, MA', 'Male'),
('Emma', 'Thomas', '707 Willow Place, Portland, OR', 'Female'),
('Lucas', 'Jackson', '808 Fir Circle, Las Vegas, NV', 'Male'),
('Ava', 'White', '909 Cypress Avenue, Atlanta, GA', 'Female'),
('Ethan', 'Harris', '1010 Cherry Lane, Houston, TX', 'Male'),
('Mia', 'Martin', '1111 Palm Boulevard, Phoenix, AZ', 'Female'),
('Alexander', 'Garcia', '1212 Chestnut Street, Orlando, FL', 'Male'),
('Isabella', 'Martinez', '1313 Hickory Drive, Dallas, TX', 'Female'),
('William', 'Lopez', '1414 Poplar Way, San Diego, CA', 'Male'),
('Amelia', 'Gonzalez', '1515 Magnolia Circle, Charlotte, NC', 'Female'),
('Elijah', 'Clark', '1616 Dogwood Avenue, Nashville, TN', 'Male'),
('Charlotte', 'Rodriguez', '1717 Acacia Court, San Jose, CA', 'Female');